# Generated by Django 3.2.4 on 2021-10-29 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='division',
            field=models.CharField(default='NL', max_length=2),
            preserve_default=False,
        ),
    ]
