# Generated by Django 3.2.4 on 2021-10-29 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsApp', '0002_team_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='abv',
            field=models.CharField(default='abv', max_length=3),
            preserve_default=False,
        ),
    ]
