# Generated by Django 3.2.4 on 2021-10-30 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statsApp', '0005_auto_20211030_0206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamelog',
            old_name='game_1_team1score',
            new_name='game_1_team1_score',
        ),
        migrations.RenameField(
            model_name='gamelog',
            old_name='game_1_team2score',
            new_name='game_1_team2_score',
        ),
        migrations.RenameField(
            model_name='gamelog',
            old_name='game_2_team1score',
            new_name='game_2_team1_score',
        ),
        migrations.RenameField(
            model_name='gamelog',
            old_name='game_3_team1score',
            new_name='game_3_team1_score',
        ),
        migrations.RenameField(
            model_name='gamelog',
            old_name='game_3_team2score',
            new_name='game_3_team2_score',
        ),
        migrations.AddField(
            model_name='gamelog',
            name='player1',
            field=models.ForeignKey(blank=True, limit_choices_to={False}, null=True, on_delete=django.db.models.deletion.CASCADE, to='statsApp.player'),
        ),
    ]
