# Generated by Django 3.2.4 on 2021-10-30 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statsApp', '0006_auto_20211030_0217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamelog',
            name='player1',
        ),
    ]
