# Generated by Django 3.2.4 on 2021-10-30 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statsApp', '0009_auto_20211030_0228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamelog',
            options={'ordering': ['date']},
        ),
        migrations.CreateModel(
            name='PlayerPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_bats', models.IntegerField(default=0)),
                ('hits', models.IntegerField(default=0)),
                ('doubles', models.IntegerField(default=0)),
                ('triples', models.IntegerField(default=0)),
                ('hrs', models.IntegerField(default=0)),
                ('rbis', models.IntegerField(default=0)),
                ('k', models.IntegerField(default=0)),
                ('bb', models.IntegerField(default=0)),
                ('game_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statsApp.gamelog')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statsApp.player')),
            ],
        ),
    ]
