# Generated by Django 3.2.4 on 2021-10-30 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statsApp', '0010_auto_20211030_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelog',
            name='team1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='team1', to='statsApp.team'),
        ),
        migrations.AlterField(
            model_name='gamelog',
            name='team2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='team2', to='statsApp.team'),
        ),
        migrations.AlterField(
            model_name='playerperformance',
            name='game_log',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='statsApp.gamelog'),
        ),
        migrations.AlterField(
            model_name='playerperformance',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='statsApp.player'),
        ),
    ]
