# Generated by Django 3.2.4 on 2021-10-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsApp', '0013_alter_player_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='D_value',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='team',
            name='average_run_scored',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='team',
            name='average_runs_allowed',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4),
        ),
    ]
