# Generated by Django 3.2.4 on 2021-10-23 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statsApp', '0002_auto_20211023_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='osp',
            new_name='ops',
        ),
    ]
