# Generated by Django 3.2.4 on 2021-10-30 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statsApp', '0003_team_abv'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('team1victories', models.IntegerField(default=0)),
                ('team2ictories', models.IntegerField(default=0)),
                ('game1team1score', models.IntegerField(default=0)),
                ('game1team2score', models.IntegerField(default=0)),
                ('game2team1score', models.IntegerField(default=0)),
                ('game3team1score', models.IntegerField(blank=True, default=0)),
                ('game3team2score', models.IntegerField(blank=True, default=0)),
                ('team1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='statsApp.team')),
                ('team2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='statsApp.team')),
            ],
        ),
    ]
