# Generated by Django 3.2.4 on 2021-10-30 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statsApp', '0004_gamelog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamelog',
            old_name='game1team1score',
            new_name='game_1_team1score',
        ),
        migrations.RenameField(
            model_name='gamelog',
            old_name='game1team2score',
            new_name='game_1_team2score',
        ),
        migrations.RenameField(
            model_name='gamelog',
            old_name='game2team1score',
            new_name='game_2_team1score',
        ),
        migrations.RenameField(
            model_name='gamelog',
            old_name='game3team1score',
            new_name='game_3_team1score',
        ),
        migrations.RenameField(
            model_name='gamelog',
            old_name='game3team2score',
            new_name='game_3_team2score',
        ),
        migrations.RenameField(
            model_name='gamelog',
            old_name='team1victories',
            new_name='team_1_victories',
        ),
        migrations.RenameField(
            model_name='gamelog',
            old_name='team2ictories',
            new_name='team_2_victories',
        ),
    ]
