# Generated by Django 3.2.4 on 2021-10-23 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statsApp', '0004_auto_20211023_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='avgra',
        ),
        migrations.RemoveField(
            model_name='team',
            name='avgrs',
        ),
    ]
