# Generated by Django 3.2.4 on 2021-10-30 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statsApp', '0007_remove_gamelog_player1'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelog',
            name='player1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='statsApp.player'),
        ),
    ]
