# Generated by Django 3.2.4 on 2021-10-30 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statsApp', '0012_gamelog_game_2_team2_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['name']},
        ),
    ]
