# Generated by Django 3.2.4 on 2021-10-30 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statsApp', '0015_rename_average_run_scored_team_average_runs_scored'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamelog',
            options={'ordering': ['-date']},
        ),
    ]
